#!/usr/bin/env python3

import os
import re
import sys

local_repository = os.path.dirname(__file__)
field_regex = r'\{\{([a-zA-Z0-9]+?)\}\}'


with open(f"{local_repository}/templates/{sys.argv[1]}.json", 'r') as f:
    template = f.read()
    
matches = list(re.finditer(field_regex, template, re.MULTILINE))


# Deduplicate names
field_names = list(set([match.group(1) for match in matches]))
field_values = []
print(f"Found {len(field_names)}")

# Get values from input
for field_name in field_names:
    field_values.append(input(f"{field_name}: "))

# Substitute values
for field_name, field_value in zip(field_names, field_values):
    template = re.sub('\{\{' + field_name + '\}\}', field_value, template, flags=re.MULTILINE)
print('=' * 16)
    
# Output to STDERR
print(template, file=sys.stderr)
